<h4> Tensors in PyTorch</h4>

Tensors are the core data structure in PyTorch.
They are similar to NumPy arrays but support:
- GPU acceleration
- Automatic differentiation

Example:

In [2]:
import torch

x = torch.tensor([[1, 2], [3, 4]])
print(x)
print(x.shape)
print(x.size())

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.Size([2, 2])


In [ ]:
# From Python list
a = torch.tensor([1, 2, 3])

# Zeros and ones
b = torch.zeros(3, 4)
c = torch.ones(2, 2)

# Random values
d = torch.rand(3, 3)
e = torch.randn(3, 3)
# randn() - normal distribution
# rand() - uniform distribution

# similar to NumPy
f = torch.randn(5)

In [8]:
a, b, c, d, e, f

(tensor([1, 2, 3]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1.],
         [1., 1.]]),
 tensor([[0.7950, 0.0343, 0.1164],
         [0.6356, 0.2834, 0.0455],
         [0.3119, 0.3341, 0.4497]]),
 tensor([[-0.8262,  0.1700,  1.0449],
         [-0.5896,  0.5027, -1.7493],
         [-0.7510,  1.6314, -0.1213]]),
 tensor([-0.3912, -1.0995, -0.1320,  0.0778, -0.7971]))